# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RenovateIssueAction < Formula
  desc "Create, update, and close GitHub Issues with GitHub Actions according to Renovate Pull Requests
"
  homepage "https://github.com/suzuki-shunsuke/renovate-issue-action"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/renovate-issue-action/releases/download/v0.1.1/renovate-issue-action_darwin_arm64.tar.gz"
      sha256 "e2d79389db89f2485228e84c06d71af5cde85f34b9b081992fa2e00fa54863a1"

      def install
        bin.install "renovate-issue-action"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/renovate-issue-action/releases/download/v0.1.1/renovate-issue-action_darwin_amd64.tar.gz"
      sha256 "b027bfa83063e075e87adebbded064d7da1b102509aca890e8fc8f3596524000"

      def install
        bin.install "renovate-issue-action"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suzuki-shunsuke/renovate-issue-action/releases/download/v0.1.1/renovate-issue-action_linux_arm64.tar.gz"
      sha256 "673dd9f17aaeafac9faafea29bc472730769ecb64150bc97e4db5883cec98ff3"

      def install
        bin.install "renovate-issue-action"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/renovate-issue-action/releases/download/v0.1.1/renovate-issue-action_linux_amd64.tar.gz"
      sha256 "f4c5209c467c1cd7631b48be2c59bfd8d77d0a623a68c2b27e0e6278b9f3fec6"

      def install
        bin.install "renovate-issue-action"
      end
    end
  end

  test do
    system "#{bin}/renovate-issue-action --version"
  end
end
