# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RenovateIssueAction < Formula
  desc "Create, update, and close GitHub Issues with GitHub Actions according to Renovate Pull Requests
"
  homepage "https://github.com/suzuki-shunsuke/renovate-issue-action"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/renovate-issue-action/releases/download/v0.2.3/renovate-issue-action_darwin_arm64.tar.gz"
      sha256 "1c9b46fdb75a7bbe6f1f7962d8110d0cfa428141f8b293eb3bf6e3dde4765ea0"

      def install
        bin.install "renovate-issue-action"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/renovate-issue-action/releases/download/v0.2.3/renovate-issue-action_darwin_amd64.tar.gz"
      sha256 "3fd7a89605e32e7499e4594c555967e9f28607eedfe846b1c0c2ce2d6c93910b"

      def install
        bin.install "renovate-issue-action"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/renovate-issue-action/releases/download/v0.2.3/renovate-issue-action_linux_amd64.tar.gz"
      sha256 "8f8be06718c8569019b62adf1b2755f2b9bfaf78d6154a049f2ce2b10ca1fa2b"

      def install
        bin.install "renovate-issue-action"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suzuki-shunsuke/renovate-issue-action/releases/download/v0.2.3/renovate-issue-action_linux_arm64.tar.gz"
      sha256 "22859f02f79167cc41445de73b0d0080a953f43996a6368e876fd49288dd12ad"

      def install
        bin.install "renovate-issue-action"
      end
    end
  end

  test do
    system "#{bin}/renovate-issue-action --version"
  end
end
